# Generated by Django 4.0.4 on 2022-05-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_users_remove_cars_id_alter_cars_reg_lessee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessee',
            name='id',
            field=models.AutoField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
