# Generated by Django 4.0.4 on 2022-05-05 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_lessee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessee',
            old_name='reg',
            new_name='carreg',
        ),
        migrations.RenameField(
            model_name='lessee',
            old_name='email',
            new_name='useremail',
        ),
    ]
