# Generated by Django 4.0.4 on 2022-05-07 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_reg_lessee_carreg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessee',
            name='carreg',
        ),
        migrations.RemoveField(
            model_name='lessee',
            name='useremail',
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
    ]
