# Generated by Django 4.0.4 on 2022-05-07 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('reg', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('fabric', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('info', models.TextField()),
            ],
        ),
    ]
